[package]
name = "qwik-optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
oxc = { version = "*", features = ["full"] }
thiserror = "2.0.11"
base64 = "0.22.1"
anyhow = "1.0.95"
path-slash = "0.2.1"
